from enum import Enum

class OrbitEnum(Enum):
    NAME = 1
    APOAPSIS = 2
    PERIAPSIS = 3
    BODY = 4
    PERIOD = 5
    INCLINATION = 6
    ECCENTRICITY = 7
    SEMIMAJORAXIS = 8
    SEMIMINORAXIS = 9
    LAN = 10
    LONGITUDEOFASCENDINGNODE = 11
    ARUGUMENTOFPERIAPSIS = 12
    TRUEANOMALY = 13
    MEANANOMALYATEPOCH = 14
    EPOCH = 15
    TRANSITION = 16
    POSITION = 17
    VELOCITY = 18
    NEXTPATCH = 19
    NEXTPATCHETA = 20
    ETA = 21
    HASNEXTPATCH = 22
    