# Suffix parent: SHIP (116)
# Suffix class span: 1 - 59

from enum import Enum

class ShipEnum(Enum):
    CONTROL = 1
    BEARING = 2
    HEADING = 3
    MAXTHRUST = 4
    MAXTHRUSTAT = 5
    AVAILABLETHRUST = 6
    AVAILABLETHRUSTAT = 7
    FACING = 8
    BOUNDS = 9
    MASS = 10
    WETMASS = 11
    DRYMASS = 12
    DYNAMICPRESSURE = 13
    Q = 14
    VERTICALSPEED = 15
    GROUNDSPEED = 16
    AIRSPEED = 17
    SHIPNAME = 18
    NAME = 19
    STATUS = 20
    DELTAV = 21
    STAGEDELTAV = 22
    STAGENUM = 23
    TYPE = 24
    STARTTRACKING = 25
    STOPTRACKING = 26
    SIZECLASS = 27
    ANGULARMOMENTUM = 28
    ANGULARVEL = 29
    SENSORS = 30
    LOADED = 31
    UNPACKED = 32
    LOADDISTANCE = 33
    ISDEAD = 34
    PATCHES = 35
    ROOTPART 36
    CONTROLPART = 37
    PARTS = 38
    DOCKINGPORTS = 39
    ELEMENTS = 40
    RESOURCES = 41
    PARTSNAMED = 42
    PARTSNAMEDREGEX = 43
    PARTSTITLED = 44
    PARTSTITLEDREGEX = 45
    PARTSTAGGED = 46
    PARTSTAGGEDREGEX = 47
    PARTSDUBBED = 48
    PARTSDUBBEDREGEX = 49
    MODULESNAMED = 50
    PARTSINGROUP = 51
    MODULESINGROUP = 52
    ALLTAGGEDPARTS = 53
    CREWCAPACITY = 54
    CREW = 55
    CONNECTION = 56
    MESSAGES = 57
    DELTAVVACUUM = 58
    BURNTIME = 59 
